-- Create an empty database. Name of the database: 
SET storage_engine= InnoDB;
SET FOREIGN_KEY_CHECKS = 1;
CREATE DATABASE IF NOT EXISTS TV;
use TV;
-- Cleaning
DROP TABLE IF EXISTS APPEARANCE;
DROP TABLE IF EXISTS VIP;
DROP TABLE IF EXISTS TV_CHANNEL;
-- Tables
CREATE TABLE VIP(
	SSN CHAR(20) NOT NULL,
	VIPName CHAR(50) NOT NULL ,
	Surname CHAR(50) NOT NULL ,
	Employment CHAR(50),
    PRIMARY KEY (SSN)
);
CREATE TABLE TV_CHANNEL(
    CodC SMALLINT NOT NULL,
    TVName CHAR(20) NOT NULL,
    Frequency DOUBLE(10,3) NOT NULL,
    Broadcaster CHAR(20) NOT NULL,
    PRIMARY KEY(CodC)
);
CREATE TABLE APPEARANCE (
	SSN CHAR(20) NOT NULL,
	Date DATE NOT NULL,
	StartTime TIME NOT NULL,
	EndTime TIME NOT NULL ,
	CodC SMALLINT NOT NULL,
	PRIMARY KEY (SSN, Date, StartTime),
	FOREIGN KEY (SSN) REFERENCES VIP(SSN) 
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (CodC) REFERENCES TV_CHANNEL(CodC) 
	ON DELETE CASCADE ON UPDATE CASCADE
);